zama-ai/concrete-core

- concrete-core/src/commons/mod.rs
- concrete-csprng/build.rs
- concrete-csprng/src/seeders/implem/rdseed.rs
- concrete-csprng/src/seeders/implem/unix.rs
- concrete-csprng/src/seeders/mod.rs
closes https://github.com/zama-ai/concrete-core-internal/issues/136
closes https://github.com/zama-ai/concrete-core-internal/issues/143
if a seeder requires specific hardware features or OS features (among
other things) the availability of such a seeder on the current machine can
be checked through a call to `is_available` that was added to the Seeder
trait and implemented for existing seeders
> feat(csprng): add API to check availability of seeders on current machine

- concrete-core-test/src/default.rs
- concrete-core-test/src/fftw.rs
- concrete-core/src/backends/fftw/implementation/engines/glwe_ciphertext_ggsw_ciphertext_discarding_external_product.rs
- concrete-core/src/backends/fftw/implementation/engines/glwe_ciphertext_ggsw_ciphertext_external_product.rs
- concrete-core/src/backends/fftw/private/crypto/bootstrap/fourier/mod.rs
- concrete-core/src/backends/fftw/private/crypto/ggsw/fourier.rs
The external_product function was copied (and slightly adapted) into the GGSW implementation. In order not to break anything, the function inside the FourierBootstrapKey was also kept, but we need to refactor this to avoid the current code duplication.
> Refactor external product

- concrete-core-bench/Cargo.toml
- concrete-core-bench/src/default.rs
- concrete-core-bench/src/main.rs
- concrete-core-fixture/Cargo.toml
- concrete-core/Cargo.toml
- concrete-core/src/backends/default/implementation/engines/lwe_bootstrap_key_creation.rs
- concrete-core/src/backends/default/implementation/engines/mod.rs
- concrete-core/src/backends/fftw/private/crypto/ggsw/fourier.rs
- concrete-core/src/commons/crypto/bootstrap/mod.rs
- concrete-core/src/commons/crypto/bootstrap/standard/mod.rs
- concrete-core/src/commons/crypto/ggsw/levels.rs
- concrete-core/src/commons/crypto/ggsw/standard.rs
- concrete-core/src/commons/crypto/gsw/ciphertext.rs
- concrete-core/src/commons/crypto/gsw/levels.rs
- concrete-core/src/commons/crypto/secret/generators/encryption.rs
- concrete-core/src/commons/crypto/secret/glwe.rs
- concrete-core/src/commons/crypto/secret/lwe.rs
- concrete-core/src/commons/math/random/generator.rs
- concrete-core/src/commons/math/tensor/tensor.rs
- concrete-core/src/prelude.rs
This PR adds an engine in the default backend that implements the parallel counterpart of the bootstrap key creation.
> Add a parallel engine to the default one

- concrete-commons/src/key_kinds.rs
- concrete-core-fixture/src/generation/prototypes/glwe_secret_key.rs
- concrete-core-fixture/src/generation/prototypes/lwe_secret_key.rs
- concrete-core/src/backends/default/implementation/entities/cleartext.rs
- concrete-core/src/backends/default/implementation/entities/cleartext_vector.rs
- concrete-core/src/backends/default/implementation/entities/ggsw_ciphertext.rs
- concrete-core/src/backends/default/implementation/entities/glwe_ciphertext.rs
- concrete-core/src/backends/default/implementation/entities/glwe_ciphertext_vector.rs
- concrete-core/src/backends/default/implementation/entities/glwe_secret_key.rs
- concrete-core/src/backends/default/implementation/entities/gsw_ciphertext.rs
- concrete-core/src/backends/default/implementation/entities/lwe_bootstrap_key.rs
- concrete-core/src/backends/default/implementation/entities/lwe_keyswitch_key.rs
- concrete-core/src/backends/default/implementation/entities/lwe_secret_key.rs
- concrete-core/src/backends/default/implementation/entities/packing_keyswitch_key.rs
- concrete-core/src/backends/default/implementation/entities/plaintext.rs
- concrete-core/src/backends/default/implementation/entities/plaintext_vector.rs
- concrete-core/src/backends/fftw/private/crypto/bootstrap/fourier/mod.rs
- concrete-core/src/backends/fftw/private/crypto/ggsw/fourier.rs
- concrete-core/src/backends/fftw/private/crypto/glwe/fourier.rs
- concrete-core/src/commons/crypto/bootstrap/standard/mod.rs
- concrete-core/src/commons/crypto/encoding/cleartext.rs
- concrete-core/src/commons/crypto/encoding/plaintext.rs
- concrete-core/src/commons/crypto/ggsw/standard.rs
- concrete-core/src/commons/crypto/glwe/ciphertext.rs
- concrete-core/src/commons/crypto/glwe/list.rs
- concrete-core/src/commons/crypto/gsw/ciphertext.rs
- concrete-core/src/commons/crypto/secret/glwe.rs
- concrete-core/src/commons/crypto/secret/lwe.rs
- concrete-csprng/src/seeders/mod.rs
closes https://github.com/zama-ai/concrete-core-internal/issues/161
New clippy lint asks to implement Eq in addition to PartialEq if all members of a struct are Eq.
This PR fixes the build issue by providing derive(Eq) to the offending structs.
Not sure if the release notes should be updated to indicate the classes deriving Eq now
~~* [ ] Check for breaking changes and add them to commit …
> chore(lint): fix clippy::derive-partial-eq-without-eq lint

- concrete-core/src/backends/fftw/private/crypto/bootstrap/fourier/mod.rs
- concrete-core/src/backends/fftw/private/crypto/bootstrap/fourier/tests.rs
- concrete-core/src/backends/fftw/private/crypto/ggsw/fourier.rs
https://github.com/zama-ai/concrete-core-internal/issues/151
This PR transfers the private implementation of cmux in the FFTW backend from the Fourier bootstrapping key to the Fourier GGSW ciphertext.
> refactor(fftw): transfer cmux from fourier bsk to fourier ggsw

- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_conversion.rs
The current fixture is bugged (the input and output are swapped in the processing of the context)
> fix(fixture): fix the LWE ciphertext conversoin fixture

- concrete-core-bench/Cargo.toml
- concrete-core-fixture/Cargo.toml
- concrete-core-fixture/src/generation/synthesizing/cleartext.rs
- concrete-core-fixture/src/generation/synthesizing/cleartext_vector.rs
- concrete-core-fixture/src/generation/synthesizing/container.rs
- concrete-core-fixture/src/generation/synthesizing/ggsw_ciphertext.rs
- concrete-core-fixture/src/generation/synthesizing/glwe_ciphertext.rs
- concrete-core-fixture/src/generation/synthesizing/glwe_ciphertext_vector.rs
- concrete-core-fixture/src/generation/synthesizing/glwe_secret_key.rs
- concrete-core-fixture/src/generation/synthesizing/lwe_bootstrap_key.rs
- concrete-core-fixture/src/generation/synthesizing/lwe_ciphertext.rs
- concrete-core-fixture/src/generation/synthesizing/lwe_ciphertext_vector.rs
- concrete-core-fixture/src/generation/synthesizing/lwe_ciphertext_vector_glwe_ciphertext_packing_keyswitch_key.rs
- concrete-core-fixture/src/generation/synthesizing/lwe_keyswitch_key.rs
- concrete-core-fixture/src/generation/synthesizing/lwe_secret_key.rs
- concrete-core-fixture/src/generation/synthesizing/plaintext.rs
- concrete-core-fixture/src/generation/synthesizing/plaintext_vector.rs
- concrete-core-test/Cargo.toml
closes https://github.com/zama-ai/concrete-core-internal/issues/189
- as default_backend is used to create all test entities prototypes it is
required to have the default_backend feature enabled at all times on
concrete-core-fixture, remove corresponding feature-gating and feature
~~* [ ] Check for breaking changes and add them to commit message following the conventional commit …
> chore(core_fixture): remove the default_backend feature

- concrete-csprng/src/generators/implem/aesni/generator.rs
- concrete-csprng/src/generators/implem/soft/generator.rs
- concrete-csprng/src/generators/mod.rs
closes https://github.com/zama-ai/concrete-core-internal/issues/186
Change the test a little bit to be sure we catch the panic when
unwrapping on the last None value, None is mapped to a specific string
that can be expected to check the test panics in the right place
> test(csprng): update test_bounded_none_should_panic to catch right panic

- .github/workflows/aws_tests_slab_beta.yml
`github.head_ref` context variable is not available for `workflow_dispatch` event. However, in this event `github.ref` is usable and appears to have the same content than `head_ref`.
~~* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)~~
> fix(ci): use available context var on workflow dispatch

- concrete-core-bench/src/fftw.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_conversion.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-fixture/src/generation/synthesizing/glwe_ciphertext.rs
- concrete-core-test/src/fftw.rs
- concrete-core/src/backends/fftw/implementation/engines/glwe_ciphertext_conversion.rs
[`concrete-core-internal/issues/179`](https://github.com/zama-ai/concrete-core-internal/issues/179)
This adds the engine for GLWE ciphertext backwards conversion (from FFT to standard domain), including fixtures, tests and benches.
> feat(core): glwe ciphertext backwards conversion

- concrete-core-fixture/src/fixture/glwe_to_lwe_secret_key_transmutation.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_1.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_2.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_extraction.rs
- concrete-core-fixture/src/fixture/lwe_to_glwe_secret_key_transmutation.rs
- concrete-core-fixture/src/generation/prototyping/glwe_secret_key.rs
- concrete-core-fixture/src/generation/prototyping/lwe_secret_key.rs
This PR changes the logic for prototyping GLWE & LWE secret keys via a transmutation. It is necessary to implement the tensor product fixture.
> Fixture: place the prototype key transmutation in dedicated traits

- .github/workflows/aws_tests_slab_beta.yml
Send Slack notifications through the workflow file instead of Slab directly. This is done to speed up ealry usage of the CI bot without messing with the current data flow.
* ~~[ ] Tests for the changes have been added (for bug fixes / features)~~
* ~~[ ] Docs have been added / updated (for bug fixes / features)~~
* ~~[ ] The PR description links to the related issue (to link an issue, use '#XXX'.)~~
* ~~[ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)~~
* ~~[ ] The draft release description has been updated~~
> chore(ci): add slack notification when using ci-bot

- concrete-tasks/src/build.rs
- concrete-tasks/src/check.rs
- concrete-tasks/src/chore.rs
- concrete-tasks/src/main.rs
- concrete-tasks/src/test.rs
- concrete-tasks/src/utils.rs
closes https://github.com/zama-ai/concrete-core-internal/issues/219
Add a uname call and some small parsing to be able to determine the CPU on mac OS.
The uname call is required to be able to work no matter the toolchain used on mac OS as we encourage devs to override it.
I have an alternative version of this PR where we don't crash if we fail to get infos on mac OS, here we stop if encounter an error.
~~* [ ] The draft release description has …
> chore(tasks): make tasks usable on M1 macs

- concrete-core-fixture/Cargo.toml
- concrete-core-fixture/src/generation/mod.rs
- concrete-core-fixture/src/generation/prototyping/lwe_bootstrap_key.rs
closes https://github.com/zama-ai/concrete-core-internal/issues/185
allows to benefit from the parallel algorithms in the
DefaultParallelEngine, so currently only bootstrap key, though as it's the
most costly it could prove to be a nice improvement (hopefully)
has to wait on https://github.com/zama-ai/concrete-core/pull/40
[conventional-breaking]: …
> feat(core_fixture): add a DefaultParallelEngine in the Maker

- concrete-core/src/commons/math/polynomial/list.rs
- concrete-core/src/commons/math/polynomial/monomial.rs
- concrete-core/src/commons/math/polynomial/polynomial.rs
~~### Resolves: `<link_your_issue_here>`~~
New nightly toolchain breaking the build, should we consider moving ahead with https://github.com/zama-ai/concrete-core-internal/issues/192 ?
add Eq when PartialEq is already derived
~~* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)~~
~~* [ ] Check for breaking changes and add them to commit message following …
> chore(core): fix clippy lint from latest nightly toolchain

- concrete-core/src/backends/fftw/implementation/engines/glwe_ciphertext_conversion.rs
- concrete-core/src/backends/fftw/private/crypto/glwe/fourier.rs
- concrete-core/src/commons/math/polynomial/list.rs
- concrete-core/src/commons/math/polynomial/monomial.rs
- concrete-core/src/commons/math/polynomial/polynomial.rs
closes https://github.com/zama-ai/concrete-core-internal/issues/215
now allows to call the function on an immutable ciphertext
if we need a version that does not perform copies and is okay to thrash the original ciphertext we can add it back, but I could not find other callsites, so I think this is ok for now
[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-chan …
> feat(core): update fill_with_backward_fourier for FourierGlweCiphertext

- concrete-tasks/src/chore.rs
cargo fmt does not accept features the way it was done. It also does not run any compilation, so we can safely run it without arguments with the latest nightly toolchains
> chore(tasks): no need for features when using cargo fmt

- concrete-core-bench/src/main.rs
There was a line missing in concrete-core-bench for the amortized PBS.
> feat(cuda): fix benchmark for the amortized PBS

- .github/workflows/aws_tests_gpu_slab_beta.yml
- .github/workflows/aws_tests_slab_beta.yml
Some under indented sections made that workflow impossible to be remotely triggered.
Also the concurrency group name has been enhanced to be able to run GPU and CPU in parallel. Now only a run with the git ref and the same AWS AMI would cancel any previous on-going run.
~~* [ ] The PR description links to the related issue (to link an issue, use '#XXX'.)~~
[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking …
> fix(ci): fix workflow file format and concurrency for aws gpu tests

- concrete-commons/src/dispersion.rs
- concrete-commons/src/parameters.rs
- concrete-core/src/backends/fftw/private/math/fft/polynomial.rs
- concrete-core/src/commons/crypto/lwe/ciphertext.rs
- concrete-core/src/commons/crypto/lwe/keyswitch.rs
- concrete-core/src/commons/crypto/lwe/list.rs
- concrete-core/src/commons/math/decomposition/decomposer.rs
- concrete-core/src/commons/math/decomposition/mod.rs
- concrete-core/src/commons/math/decomposition/term.rs
- concrete-core/src/commons/math/polynomial/polynomial.rs
- concrete-npe/src/key_dispersion.rs
- concrete-npe/src/lib.rs
- concrete-npe/src/operators.rs
This PR applies the underscore escaping to all the latex in docs comments in concrete-core, it makes writing formal defs easier as we don't have changes coming from other parts of the code base when applying the underscores
> chore(core): apply underscore escaping to all the documentation

- concrete-core/docs/backends/backend_fftw.md
Replaces a mention to transmute_glwe_secret_key_to_lwe_secret_key by transform_glwe_secret_key_to_lwe_secret_key.
> docs(core): updates the FFTW backend tutorial

- .github/workflows/aws_tests_gpu.yml
- .github/workflows/aws_tests_gpu_slab_beta.yml
Add the installation of the frozen toolchain required for xtask calls
> chore(ci): add frozen toolchain installation for xtask in GPU workflows

- .github/pull_request_template.md
Just updates the template PR to refer to slab.
> chore(core): modify template PR to use slab-ci for tests

- concrete-core/src/commons/math/random/tests.rs
The test for Gaussian distribution in concrete-core is still flaky, because we don't draw enough inputs.
> Increase the amount of samples in the gaussian distribution test

- concrete-core-ffi/src/seeders/unix_seeder.rs
we were being overly cautious, a secret here is like a secret key
FYI @BourgerieQuentin and @mayeul-zama 
> chore(ffi): do not limit creations of UnixSeeder from a single secret

- concrete-csprng/Cargo.toml
- concrete-csprng/src/generators/aes_ctr/generic.rs
last is the one used in tight loops, get_bound is used rarely, removed
bound which makes the struct 128 + 64 = 192 bits smaller or 24 bytes less
> refactor(csprng): remove the bound index which is a near duplicate of last

- concrete-core/src/commons/crypto/gsw/tests.rs
- concrete-core/src/commons/crypto/lwe/ciphertext.rs
refs https://github.com/zama-ai/concrete-core-internal/issues/308
refs https://github.com/zama-ai/concrete-core-internal/issues/347
closes https://github.com/zama-ai/concrete-core-internal/issues/163
disable gsw tests as the corresponding functions are not used
to be re-enabled once we do something with them
> fix(test): disable gsw and lower noise on a toy example

- concrete-core-fixture/src/fixture/glwe_ciphertext_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_discarding_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_discarding_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_discarding_trivial_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_trivial_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_trivial_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_discarding_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_discarding_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_trivial_decryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_trivial_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_vector_zero_encryption.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_zero_encryption.rs
- concrete-core-fixture/src/fixture/glwe_seeded_ciphertext_encryption.rs
- concrete-core-fixture/src/fixture/glwe_seeded_ciphertext_to_glwe_ciphertext_transformation.rs
- concrete-core-fixture/src/fixture/glwe_seeded_ciphertext_vector_encryption.rs
- concrete-core-fixture/src/fixture/glwe_seeded_ciphertext_vector_to_glwe_ciphertext_vector_transformation.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_extraction.rs
we rarely use GlweDimension > 2 (if ever) and the zero encryption test seems to be
the one that slows our whole test suite down, this should allow for much
faster PRs
> fix(test): update zero encryption vector fixture to use realistic params

- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/glwe_ciphertext_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/glwe_ciphertext_discarding_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
Implements: 
- Conversion from GlweCiphertextView64 to CudaGlweCiphertext64,
- Discarding conversion from CudaGlweCiphertext64 to GlweCiphertextMutView64
> Implement conversions between GlweCiphertextView64 and CudaGlweCiphertext64

- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
Implements: 
- Conversion from LweCiphertextView64 to CudaLweCiphertext64,
- Discarding conversion from CudaLweCiphertext64 to LweCiphertextMutView64
> Implement conversions between LweCiphertextView64 and CudaLweCiphertext64

- concrete-core/src/backends/cuda/implementation/engines/cuda_amortized_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_bootstrap.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_keyswitch.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_discarding_keyswitch.rs
- concrete-core/src/backends/cuda/implementation/entities/glwe_ciphertext.rs
- concrete-core/src/backends/cuda/implementation/entities/glwe_ciphertext_vector.rs
- concrete-core/src/backends/cuda/implementation/entities/lwe_bootstrap_key.rs
- concrete-core/src/backends/cuda/implementation/entities/lwe_ciphertext.rs
- concrete-core/src/backends/cuda/implementation/entities/lwe_ciphertext_vector.rs
- concrete-core/src/backends/cuda/implementation/entities/lwe_keyswitch_key.rs
- concrete-core/src/backends/cuda/private/crypto/bootstrap/mod.rs
- concrete-core/src/backends/cuda/private/crypto/glwe/ciphertext.rs
- concrete-core/src/backends/cuda/private/crypto/glwe/list.rs
- concrete-core/src/backends/cuda/private/crypto/keyswitch/mod.rs
- concrete-core/src/backends/cuda/private/crypto/lwe/ciphertext.rs
- concrete-core/src/backends/cuda/private/crypto/lwe/list.rs
Some getters in the private API of the Cuda backend are redundant so we prefer to remove them.
> chore(cuda): remove redundant getters in the cuda backend

- concrete-commons/src/parameters.rs
This adds PartialOrd, Ord derives for GlweSize, LweSize, GlweDimension, GlweSize so that they can be used on types
which can then derive PartialOrd, Ord to be used as Keys for BTreeMap.
> feat(core): add PartialOrd, Ord derives to [Glwe/Lwe][Dimension/Size]

- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_conversion.rs
This adds some discarding conversion between GPU and CPU that are needed for concrete-boolean
> feat(cuda): add some missing cuda discarding lwe conversion

- concrete-core/src/backends/cuda/private/device.rs
- concrete-tasks/src/test.rs
Updates the allocate_and_copy private test to use CudaVec instead of pointers.
> fix(cuda): update allocate_and_copy test

- concrete-commons/src/dispersion.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_ggsw_ciphertext_discarding_external_product.rs
- concrete-core-fixture/src/fixture/glwe_ciphertext_ggsw_ciphertext_external_product.rs
- concrete-core-fixture/src/fixture/glwe_ciphertexts_ggsw_ciphertext_fusing_cmux.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_addition.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_1.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_keyswitch.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_subtraction.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_fusing_addition.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_fusing_subtraction.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_addition.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_subtraction.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_fusing_addition.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_fusing_subtraction.rs
- concrete-core/src/commons/crypto/gsw/tests.rs
- concrete-npe/src/key_dispersion.rs
- concrete-npe/src/lib.rs
- concrete-npe/src/operators.rs
- concrete-npe/src/tools.rs
Replace remove torus type generics by a function parameter log2_modulus in all relevant functions in concrete-npe.
- the generics torus type in only ever used to extract the number of bits, so we don't loose any useful information by only giving the log2_modulus
- we only ask for the information we need so it's less constraining for callers
- the generics are contaminating, which forces us to use generics too in the optimizer (log2_modulus -> generic type) is not possible (or very ugly: match log2_modulus {32 => f::<u32>(...), 64 => f::<u64>(...))
- for another client of concrete-npe using generics, it's possible to get the log2_modulus from the generic type (genric_type -> log2_modulus) is clean (f(..., T::BITS))
- we add a function parameter but we also remove a generic type, so we …
> feat(concrete_npe): remove torus type generics

- Cargo.toml
- concrete-core/Cargo.toml
- concrete-npe/Cargo.toml
- we use multiple location dep declaration, path is used for local builds
or for builds using the git repo
- the version is used for crates published on crates.io
> chore(crates): change the way to declare deps to be git friendly

- concrete-core/src/backends/default/implementation/engines/default_engine/glwe_seeded_ciphertext_to_glwe_ciphertext_transformation.rs
- concrete-core/src/backends/default/implementation/engines/default_engine/glwe_seeded_vector_to_glwe_ciphertext_vector_transformation.rs
- concrete-core/src/backends/default/implementation/engines/default_engine/glwe_to_lwe_secret_key_transformation.rs
- concrete-core/src/backends/default/implementation/engines/default_engine/lwe_seeded_bootstrap_key_to_lwe_bootstrap_key_transformation.rs
- concrete-core/src/backends/default/implementation/engines/default_engine/lwe_seeded_ciphertext_vector_to_lwe_ciphertext_vector_transformation.rs
- concrete-core/src/backends/default/implementation/engines/default_engine/lwe_seeded_keyswitch_key_to_lwe_keyswitch_key_transformation.rs
- concrete-core/src/backends/default/implementation/engines/default_engine/lwe_seeded_to_lwe_ciphertext_transformation.rs
- concrete-core/src/backends/default/implementation/engines/default_engine/lwe_to_glwe_secret_key_transformation.rs
- concrete-core/src/specification/engines/glwe_seeded_ciphertext_to_glwe_ciphertext_transformation.rs
- concrete-core/src/specification/engines/glwe_seeded_ciphertext_vector_to_glwe_ciphertext_vector_transformation.rs
- concrete-core/src/specification/engines/glwe_to_lwe_secret_key_transformation.rs
- concrete-core/src/specification/engines/lwe_seeded_bootstrap_key_to_lwe_bootstrap_key_transformation.rs
- concrete-core/src/specification/engines/lwe_seeded_ciphertext_to_lwe_ciphertext_transformation.rs
- concrete-core/src/specification/engines/lwe_seeded_ciphertext_vector_to_lwe_ciphertext_vector_transformation.rs
- concrete-core/src/specification/engines/lwe_seeded_keyswitch_key_to_lwe_keyswitch_key_transformation.rs
- concrete-core/src/specification/engines/lwe_to_glwe_secret_key_transformation.rs
closes https://github.com/zama-ai/concrete-core-internal/issues/253
Some error names were wrong and got replicated through copy paste, this PR fixes it
> chore(core): fix naming of some errors

- concrete-core/src/backends/cuda/implementation/engines/cuda_amortized_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_amortized_engine/mod.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/glwe_ciphertext_vector_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_bootstrap_key_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_bootstrap.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_keyswitch.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_discarding_keyswitch.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_keyswitch_key_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
- concrete-core/src/backends/cuda/private/crypto/bootstrap/mod.rs
- concrete-core/src/backends/cuda/private/crypto/keyswitch/mod.rs
- concrete-core/src/backends/cuda/private/crypto/lwe/list.rs
- concrete-core/src/backends/cuda/private/device.rs
- concrete-core/src/backends/cuda/private/mod.rs
- concrete-core/src/commons/crypto/lwe/ciphertext.rs
+ Fix multi GPU when there are few inputs: in case the number of GPUs is lower than the number of inputs, restrict the number of GPUs used to the number of inputs.
+ Also, change some types so that it feels more natural to use them.
> fix(cuda): fix multi-GPU implementation when there are few inputs

- ci/slab.toml
In the next Slab CI bot release, the inner workings of the server change a bit. In order to have more flexibility on command declaration and EC2 profile definitions for each repositories, the configuration belongs now to each repo.
Each time a command is run from a PR, the file `ci/slab.toml` will be fetched and read from the branch the PR refers to. A great aspect of this behavior is the ability to add a new command/profile in your PR to test your code in other conditions. Another one is to avoid having hardcoded profiles structs and commands in Slab, and thus remove the need to make a release or reboot Slab in case of global configuration changes.
[conventional-breaking]: …
> ci: Add remote configuration for slab ci bot

- concrete-core/src/specification/engines/lwe_seeded_ciphertext_encryption.rs
- concrete-core/src/specification/engines/lwe_seeded_ciphertext_vector_encryption.rs
- concrete-core/src/specification/engines/lwe_seeded_ciphertext_vector_to_lwe_ciphertext_vector_transformation.rs
refs https://github.com/zama-ai/concrete-core-internal/issues/296
Some formal defs are missing for seeded entities, this is a PR to complete the definitions, this one is for the seeded LWE ciphertext vector.
> docs(core): add formal def. for seeded LWE ciphertext vector encryption

- concrete-core-bench/src/cuda.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_trivial_decryption.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_trivial_encryption.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_conversion.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_decryption.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_conversion.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_decryption.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_encryption.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_encryption.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_zero_encryption.rs
- concrete-core-fixture/src/fixture/mod.rs
- concrete-core-fixture/src/generation/synthesizing/lwe_ciphertext_vector.rs
- concrete-core-test/src/cuda.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_discarding_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
- concrete-core/src/backends/cuda/private/crypto/lwe/list.rs
This PR adds conversions between Cuda LWE ciphertext vectors & views on the CPU.
> feat(cuda): add LweCiphertextVectorView conversions

- concrete-core/src/backends/cuda/private/crypto/bootstrap/mod.rs
- concrete-core/src/backends/cuda/private/crypto/keyswitch/mod.rs
Adds implementation of Send Sync for cuda bsk and ksk.
I don't know the internals of the cuda implementation in details,
but for this change to be valid, the CudaVec's internal pointer (that is the ksk and bsk in our case)
should point to data that don't have interior mutability, which would otherwise lead to data races.
(So the ksk and bsk on the cuda side must not have buffers stored in them, or any ref count).
On a test using concrete-boolean, I got a noticable (but quickly bounded) speedup by using multiple thread + cuda
while still having correct results.
> feat(cuda): implement Send and Sync for cuda ksk and bsk

- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_glwe_ciphertext_discarding_private_functional_packing_keyswitch.rs
- concrete-npe/src/operators.rs
https://github.com/zama-ai/concrete-core-internal/issues/316
https://github.com/zama-ai/concrete-core-internal/issues/317
https://github.com/zama-ai/concrete-core-internal/issues/318
https://github.com/zama-ai/concrete-core-internal/issues/319
This PR adds the noise propagation estimates for the WoP-PBS and its constituent parts: bit extraction, circuit bootstrapping and vertical packing.
This PR also updates the private functional packing keyswitch key noise propagation estimation function and the associated fixture to remove the torus type generics.
> feat(npe): add noise propagation estimates for WoP-PBS

- concrete-core/src/backends/cuda/private/mod.rs
- concrete-core/src/backends/cuda/private/wopbs/mod.rs
- concrete-core/src/backends/cuda/private/wopbs/test.rs
- concrete-cuda/cuda/include/bootstrap.h
- concrete-cuda/cuda/src/bootstrap_wop.cu
- concrete-cuda/cuda/src/bootstrap_wop.cuh
- concrete-cuda/cuda/src/crypto/bootstrapping_key.cuh
- concrete-cuda/cuda/src/crypto/ggsw.cuh
- concrete-cuda/cuda/src/polynomial/functions.cuh
- concrete-cuda/cuda/src/polynomial/polynomial_math.cuh
- concrete-cuda/src/cuda_bind.rs
Implements a CUDA kernel that computes a CMUX tree. 
Let r be the depth of the tree: Each kernel handles an entire layer of cmuxes so that each block computes a single CMUX. We have r kernel launches, each running 2^(r-l) thread blocks with polynomial_size/params::opt threads on layer l.
This PR has with a rust test to verify the correctness of the implementation. Maybe we should remove it before merge. 
> feat(cuda): Implements the CMUX Tree on CUDA backend.

- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/ggsw_ciphertext_conversion.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
- concrete-core/src/backends/cuda/implementation/entities/ggsw_ciphertext.rs
- concrete-core/src/backends/cuda/implementation/entities/mod.rs
- concrete-core/src/backends/cuda/private/crypto/ggsw/ciphertext.rs
- concrete-core/src/backends/cuda/private/crypto/ggsw/mod.rs
- concrete-core/src/backends/cuda/private/crypto/mod.rs
These conversions may be useful future implementations on concrete-cuda side.
> feat(cuda): implement conversion between GgswCiphertext and CudaGgswCiphertext

- concrete-cuda/cuda/include/bootstrap.h
This PR solves an issue that may happen if headers in concrete-cuda are included in code compiled using a standard C/C++ compiler. 
> fix(cuda): Add a conditional macro check to remove CUDA-specific definitions when not needed

- concrete-core-bench/src/fft.rs
- concrete-core-test/src/fft.rs
- concrete-core-wasm/src/lib.rs
- concrete-core/src/backends/fft/implementation/engines/fft_engine/lwe_ciphertext_discarding_bit_extraction.rs
- concrete-core/src/backends/fft/implementation/engines/fft_engine/mod.rs
Adds bit extract to the FFT backend public API
> feat(core): add bit extract to fft backend public API

- concrete-core-bench/src/fft.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_circuit_bootstrap_boolean_vertical_packing.rs
- concrete-core-test/src/fft.rs
- concrete-core/src/backends/fft/implementation/engines/fft_engine/lwe_ciphertext_discarding_circuit_bootstrap_boolean.rs
- concrete-core/src/backends/fft/implementation/engines/fft_engine/lwe_ciphertext_vector_discarding_circuit_bootstrap_boolean_vertical_packing.rs
- concrete-core/src/backends/fft/implementation/engines/fft_engine/mod.rs
Adds circuit bootstrap & vertical packing to the FFT backend public API
> feat(core): add circuit bootstrap & vertical packing to fft backend

- .github/workflows/aws_tests_gpu_slab_beta.yml
We should be using `cargo xtask test_cuda` for that.
> fix(ci): Replaces the command used to test CUDA 11.1 in the CI.

- concrete-core-representation/src/ccr/mod.rs
- concrete-core-wasm/Cargo.toml
- concrete-core-wasm/src/lib.rs
The `LwePublicKeyGenerationEngine` signature contained a new `LwePublicKeyZeroEncryptionCount` parameter type, that was not recognized by the `concrete-core-representation` tool. That lead to the argument being parsed as `Unknown` and pruned from the `ccr` before the binding was generated. 
> fix(concrete_core_wasm): fix pruning of wrongly detected parameter arg

- concrete-core-wasm/src/lib.rs
In `concrete-core-wasm`, this commit adds a function to unwrap the parameters into a raw number.
> fix(concrete_core_wasm): add getters for sizes, and unwraps.

- concrete-core/src/backends/fft/implementation/engines/fft_engine/lwe_ciphertext_discarding_bootstrap.rs
- concrete-core/src/backends/fft/private/math/fft/mod.rs
- concrete-core/src/backends/fft/private/math/fft/tests.rs
- concrete-core/src/backends/fft/private/math/fft/x86.rs
Disabling the backwards as torus primitive that has an issue, potentially the 32 bits variant is not affected and could be re-enabled safely, for now I just played it safe and removed it altogether
> fix(core): dirty fix for fft convert backwards issue

- concrete-core/src/backends/fft/private/math/fft/mod.rs
- concrete-core/src/backends/fft/private/math/fft/tests.rs
- concrete-core/src/backends/fft/private/math/fft/x86.rs
fixes the edge case in the vectorized f64 to i64 conversion
> feat(core): fix edge cases for f64 to i64 conversion

- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_1.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_2.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_1.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_2.rs
GLWE dimension can only be 1 for the GPU implementation but we should test for k > 1 for the CPU implementation.
This PRs solves this.
> chore(core): differentiate params for pbs fixture between cpu/gpu implems

- concrete-cuda/cuda/CMakeLists.txt
The cuda_script is now removed after it's used in the CMakelists.txt file.
> chore(cuda): remove cuda_script file

- concrete-core/Cargo.toml
- concrete-core/src/backends/fft/private/crypto/wop_pbs/tests.rs
- concrete-core/src/commons/crypto/encoding/encoder.rs
- concrete-core/src/commons/crypto/glwe/keyswitch.rs
- concrete-core/src/commons/math/tensor/mod.rs
- concrete-core/src/commons/math/tensor/tensor.rs
Non wrapping functions are simply removed, they were not used.
> fix(core): remove calls to non wrapping tensor functions

- concrete-core/src/backends/default/implementation/engines/default_engine/lwe_ciphertext_discarding_extraction.rs
As pointed out here https://community.zama.ai/t/extract-a-lwe-ciphertext-from-a-rlwe-ciphertext/325/3?u=icetdrinker
our doc strings for LWE sample extractions are wrong, this PR fixes it
> chore(core): fix doc strings for LWE extraction

- concrete-cuda/cuda/include/bootstrap.h
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX187GxdY8scLwWG7PlcFDpQSdW65xjpJC4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=8bUHVLR)
> fix(cuda): Remove extra ; in bootstrap header file that lead to warnings

- concrete-cuda/cuda/include/device.h
- concrete-cuda/cuda/src/bootstrap_amortized.cuh
- concrete-cuda/cuda/src/bootstrap_low_latency.cuh
- concrete-cuda/cuda/src/bootstrap_wop.cuh
- concrete-cuda/cuda/src/device.cu
Two functions are implemented to encapsulate the asynchronous allocation and freeing of device memory. If the installed toolkit version is less than 11.2, use synchronous.
> feat(cuda): Refactor all host functions in concrete-cuda to use asynchronous allocation

- concrete-core/Cargo.toml
cargo packages everything in the concrete-core dir, and that includes some big images from our docs, let's fix that.
```
cargo package -l --allow-dirty -p concrete-core
```
shows which files get packaged
> chore(core): exclude docs from crate for publishing

- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/glwe_ciphertext_vector_conversion.rs
- concrete-cuda/cuda/include/device.h
- concrete-cuda/cuda/src/bootstrap_amortized.cuh
- concrete-cuda/cuda/src/bootstrap_low_latency.cuh
- concrete-cuda/cuda/src/bootstrap_wop.cuh
- concrete-cuda/cuda/src/device.cu
We need to check for the cuda version during compilation to ensure the async functions will compile but we also need to check for that property on runtime. 
> fix(cuda): Checks the cudaDevAttrMemoryPoolsSupported property to ensure that asynchronous allocation is supported

- .github/workflows/aws_tests_gpu_slab_beta.yml
- .github/workflows/aws_tests_slab_beta.yml
Last version of Slab CI bot imposes to add another input field to workflows meant to be triggered by Slab.
> chore(ci): adapt workflows to v0.9.x of slab ci bot

- concrete-core/Cargo.toml
- concrete-core/src/backends/cuda/private/wopbs/mod.rs
- concrete-core/src/backends/cuda/private/wopbs/test.rs
- concrete-cuda/cuda/include/bootstrap.h
- concrete-cuda/cuda/src/bootstrap_wop.cu
- concrete-cuda/cuda/src/bootstrap_wop.cuh
- concrete-cuda/cuda/src/crypto/ggsw.cuh
- concrete-cuda/src/cuda_bind.rs
This PR implements the missing parts for the vertical packing on the CUDA backend. It also contains a private test that verifies if it works.
> feat(cuda): Implements vertical packing's blind rotation and sample extraction on the CUDA backend

- .github/workflows/gpu_benchmark.yml
- .github/workflows/start_gpu_benchmark.yml
- ci/benchmark_parser.py
- ci/slab.toml
Concrete-cuda benchmarks can be run either from a Pull Request or can be started using start_gpu_benchmark.yml.
On each push on main branch this workflow will be triggered. Results are parsed and sent to Slab CI server which will in turn make them available in our Grafana instance.
> chore(ci): enable concrete-cuda benchmarks on slab

- concrete-core/src/commons/mod.rs
- test random generation tools were unsound (could divide by 0) and ranges were not respected
> chore(tools): fix test tools

- concrete-core/src/backends/fft/implementation/engines/fft_engine/glwe_ciphertext_ggsw_ciphertext_discarding_external_product.rs
- concrete-core/src/backends/fft/private/crypto/ggsw.rs
fixed a bug in the discarding external product where the previous value wasn't being discarded
> core: fix discarding external product

- concrete-core/src/backends/cuda/implementation/entities/plaintext_vector.rs
- concrete-core/src/backends/cuda/private/crypto/bootstrap/test.rs
- concrete-core/src/backends/cuda/private/wopbs/test.rs
- concrete-cuda/cuda/src/crypto/bootstrapping_key.cuh
- concrete-cuda/cuda/src/fft/bnsmfft.cuh
- concrete-tasks/src/test.rs
- Fix 8192 polynomial size pbs bug
- Modify private unit test to work on multiple polynomial sizes
- Removes some (legacy) warnings
- Fix memory leak in pbs/wopbd private tests
> Fix Cuda amortized bootstrap bug with N=8192

- concrete-core/src/backends/fft/implementation/engines/fft_engine/lwe_ciphertext_vector_discarding_circuit_bootstrap_boolean_vertical_packing.rs
- the value passed for the LUT polynomial count is not correct, unit tests prove that
> fix(core): fix wopbs memory scratch for wopbs

- concrete-cuda/cuda/include/device.h
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX17VqT1msf9jeWbdweGXmUJAtJhZqqBkc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=fVhILCF)
Without this include the Compiler cannot find cudaStream_t at link time.
> fix(cuda): include cuda_runtime.h in device.h to include the definition of cudaStream_t

- concrete-cuda/cuda/include/device.h
- concrete-cuda/cuda/src/bootstrap_amortized.cuh
- concrete-cuda/cuda/src/bootstrap_low_latency.cuh
- concrete-cuda/cuda/src/bootstrap_wop.cuh
- concrete-cuda/cuda/src/crypto/bootstrapping_key.cuh
- concrete-cuda/cuda/src/crypto/ggsw.cuh
- concrete-cuda/cuda/src/device.cu
I also define as default the use of pointers to cudaStream_t for all functions in that file.
> chore(cuda): Refactor device.cu functions to take pointers to cudaStream_t instead of void

- concrete-cuda/cuda/src/bootstrap_low_latency.cu
- concrete-cuda/cuda/src/bootstrap_wop.cu
The assert on the number of inputs for the low latency bootstrap uses #SM / 4 but it should be SM * 4 instead: with an occupancy of 50% we can launch 4*SM blocks on the device.
> fix(cuda): fix the assert on the number of inputs in the low lat pbs

- concrete-core/src/backends/cuda/private/wopbs/mod.rs
- concrete-core/src/backends/cuda/private/wopbs/test.rs
- concrete-cuda/cuda/include/bootstrap.h
- concrete-cuda/cuda/src/bootstrap_wop.cu
- concrete-cuda/cuda/src/bootstrap_wop.cuh
- concrete-cuda/src/cuda_bind.rs
LUTs are initially trivially encrypted, thus only bodies are handled. However, inside the CMUX Tree we need the zeroed mask to keep correctness of the computation.
* Implements add_padding_to_lut_async() to insert zeroed polynomials paddings . This is also done in the CPU implementation, and in the GPU case we can make use of asynchronous copies within the device to reorganize the array.
* Refactors the CMUX tree to run different trees through the y-axis of the grid.
* Refactors the CBS+VP implementation to use the tau parameters of the blind rotation host function.
> chore(cuda): Improves VP parallelization and refactors CMUX Tree to match the CPU version

- concrete-core/src/backends/cuda/private/crypto/wopbs/test.rs
- concrete-cuda/cuda/src/vertical_packing.cuh
- concrete-cuda/cuda/src/wop_bootstrap.cuh
> fix(cuda): Debug more complex cases on the CBS+VP private test

- concrete-cuda/cuda/include/boolean_gates.h
- concrete-cuda/cuda/src/CMakeLists.txt
- concrete-cuda/cuda/src/boolean_gates.cu
- concrete-cuda/cuda/src/multiplication.cuh
- concrete-cuda/cuda/src/utils/kernel_dimensions.cuh
Add AND and NOT boolean gates implementation.
> feat(cuda): add NOT and AND gates to the library

- concrete-cuda/cuda/include/bootstrap.h
- concrete-cuda/cuda/src/addition.cu
- concrete-cuda/cuda/src/bit_extraction.cu
- concrete-cuda/cuda/src/bit_extraction.cuh
- concrete-cuda/cuda/src/bootstrap_amortized.cu
- concrete-cuda/cuda/src/bootstrap_low_latency.cu
- concrete-cuda/cuda/src/circuit_bootstrap.cu
- concrete-cuda/cuda/src/circuit_bootstrap.cuh
- concrete-cuda/cuda/src/keyswitch.cu
- concrete-cuda/cuda/src/multiplication.cu
- concrete-cuda/cuda/src/negation.cu
- concrete-cuda/cuda/src/vertical_packing.cu
- concrete-cuda/cuda/src/wop_bootstrap.cu
- concrete-cuda/src/cuda_bind.rs
https://github.com/zama-ai/concrete-core-internal/issues/487
Add Rust doc for all concrete-cuda entry points
> docs(cuda): add Rust doc for all concrete-cuda entry points

- concrete-core-fixture/Cargo.toml
- concrete-core/Cargo.toml
- concrete-csprng/Cargo.toml
- concrete-csprng/src/generators/implem/mod.rs
- concrete-csprng/src/generators/implem/soft/block_cipher.rs
- concrete-csprng/src/lib.rs
- concrete-csprng/src/main.rs
closes https://github.com/zama-ai/concrete-core-internal/issues/353
- updated csprng code so that nightly is not always necessary on M1 macs (if using the fallback generator coming from aes e.g.)
- bumped version as the feature name change is a breaking change
> refactor(csprng): upgrade aes to 0.8.2 generator_soft -> generator_fallback

- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_1.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_2.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_1.rs
- concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_2.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_amortized_engine/mod.rs
- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
- concrete-cuda/cuda/src/bootstrap_amortized.cu
- concrete-cuda/cuda/src/bootstrap_low_latency.cu
- concrete-cuda/cuda/src/crypto/bootstrapping_key.cuh
Now that we have support for k>1 it is necessary to also support N=256.
> feat(cuda): Add support for the classical PBS for polynomial_size=256.

- concrete-cuda/cuda/src/bootstrap_amortized.cuh
- concrete-cuda/cuda/src/vertical_packing.cuh
By using the new `decompose_and_compress_next_polynomial()` we can shrink again the size of `accumulator_fft` to store a single polynomial. Moreover, this PR also replaces loops of the form
```
for (int i = 0; i < (glwe_dim+1) * params::opt; i++){
...
}
```
by
```
for (int i = 0; i < (glwe_dim+1); i++)
for (int j = 0; j < params::opt; j++){
...
}
```
so the compiler is capable of unrolling the inner loop.
> chore(cuda): Reduces shared memory consumption in the amortized PBS and improves loop unrolling.

- concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_bootstrap.rs
- concrete-core/src/backends/cuda/private/crypto/bootstrap/mod.rs
- concrete-core/src/backends/cuda/private/crypto/bootstrap/test.rs
- concrete-core/src/backends/cuda/private/crypto/wopbs/test.rs
- concrete-core/src/backends/cuda/private/device.rs
- concrete-cuda/cuda/src/wop_bootstrap.cu
- concrete-cuda/cuda/src/wop_bootstrap.cuh
https://github.com/zama-ai/concrete-core-internal/issues/513
as a follow up to a discussion in https://github.com/zama-ai/concrete-core/issues/332
> chore(cuda): replace synchronous copies with async ones in the private cuda backend

- concrete-cuda/cuda/src/bit_extraction.cu
- concrete-cuda/cuda/src/bootstrap_amortized.cu
- concrete-cuda/cuda/src/bootstrap_low_latency.cu
- concrete-cuda/cuda/src/circuit_bootstrap.cu
- concrete-cuda/cuda/src/vertical_packing.cu
- concrete-cuda/cuda/src/wop_bootstrap.cu
This commit moves all asserts from `host_*` methods to a single function and inserts it also in the scratch functions.
> chore(cuda): Add checks to validate inputs passed to the scratch functions

- concrete-core/src/backends/cuda/private/crypto/bootstrap/test.rs
- concrete-core/src/backends/cuda/private/crypto/wopbs/test.rs
- concrete-cuda/cuda/src/bit_extraction.cuh
- concrete-cuda/cuda/src/bootstrap_amortized.cuh
- concrete-cuda/cuda/src/bootstrap_low_latency.cuh
- concrete-cuda/cuda/src/circuit_bootstrap.cuh
- concrete-cuda/cuda/src/multiplication.cuh
- concrete-cuda/cuda/src/vertical_packing.cuh
- concrete-cuda/cuda/src/wop_bootstrap.cuh
The buffer size type used in the scratch functions was too small which led to negative values due to wrapping. This PR fixes it.
> fix(cuda): fix buffer size type in scratch
