.github/workflows/aws_tests.yml
.github/workflows/docs_core.yml

closes https://github.com/zama-ai/concrete-core-internal/issues/154
closes https://github.com/zama-ai/concrete-core-internal/issues/156
[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaki …

chore(ci): small fixes to aws_test.yml

---

concrete-commons/Cargo.toml
concrete-core-bench/Cargo.toml
concrete-core-fixture/Cargo.toml
concrete-core-test/Cargo.toml
concrete-core/Cargo.toml
concrete-csprng/Cargo.toml
concrete-npe/Cargo.toml
concrete-tasks/Cargo.toml

closes https://github.com/zama-ai/concrete-core-internal/issues/162
Update language edition to 2021
Waiting for basic checks to pass before completing the remaining tasks in the PR

chore(rust): update language edition to 2021

---

.github/workflows/aws_tests_slab_beta.yml

Format AWS tests action file to be usable by the Slab the CI-bot.

test(ci): Format AWS action file to be usable with CI bot

---

concrete-core/Cargo.toml
concrete-npe/Cargo.toml
concrete-tasks/Cargo.toml
concrete-tasks/src/main.rs

closes https://github.com/zama-ai/concrete-core-internal/issues/209
As dependabot was throwing warnings at us, I removed unused dependencies using https://github.com/est31/cargo-udeps

chore(deps): remove and update some dependencies

---

concrete-csprng/src/generators/implem/aesni/block_cipher.rs

closes https://github.com/zama-ai/concrete-core-internal/issues/217
- rdseed is not required for the AES block cipher
- update feature detection to have meaningful error message

fix(csprng): update CPU feature detection

---

.github/workflows/build.yml
.github/workflows/build_benches.yml

closes https://github.com/zama-ai/concrete-core-internal/issues/220

chore(ci): remove fftw installation that is not required anymore

---

concrete-ffi/README.md
concrete-ffi/docs/api/api.md
concrete-ffi/docs/dev/dev.md
concrete-ffi/docs/dev/instantiating_and_destroying_objects.md
concrete-ffi/docs/index.md
concrete-ffi/docs/user/user.md
concrete-ffi/tests/CMakeLists.txt

closes https://github.com/zama-ai/concrete-core-internal/issues/157

docs(ffi): add beginning of concrete-ffi docs

---

concrete-core/src/backends/fftw/private/math/fft/tests.rs

closes https://github.com/zama-ai/concrete-core-internal/issues/231

chore(fmt): fix fmt for new nightly toolchain

---

.github/ISSUE_TEMPLATE/design_document.md

closes https://github.com/zama-ai/concrete-core-internal/issues/243
Add a template for github to easily create design documents
[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-chang …

chore(github): add a design issue template

---

README.md
concrete-commons/README.md
concrete-core-bench/README.md
concrete-core-test/README.md
concrete-core/README.md
concrete-csprng/README.md
concrete-npe/README.md

closes https://github.com/zama-ai/concrete-core-internal/issues/160

chore(core): update READMEs

---

concrete-core/src/backends/fftw/private/math/fft/tests.rs

chore(core): fix nightly format

---

concrete-core/src/backends/fftw/private/math/fft/transform.rs

this should be the last commit of this kind, we will start freezing
toolchains soon for the tasks crate

chore(clippy): fix new clippy lint

---

concrete-core-ffi/README.md
concrete-core/docs/README.md
concrete-core/docs/SUMMARY.md

docs(core): update user doc welcome page

---

concrete-commons/Cargo.toml
concrete-core/Cargo.toml
concrete-npe/Cargo.toml

chore(core): bump versions for the release

---

.github/workflows/wasm_github_release.yml

Adds a github action to build and upload the `concrete-core-wasm` package.
* ~[ ] Tests for the changes have been added (for bug fixes / features)~
* ~[ ] Docs have been added / updated (for bug fixes / features)~
* ~[ ] The PR description links to the related issue (to link an issue, use '#XXX'.)~
* ~[ ] The tests on AWS have been launched and are successful (apply the `aws_test` to the PR to launch the tests on AWS)~
* ~[ ] The draft release description has been updated~
* ~[ ] Check for breaking changes and add them to commit message following the conventional commit [specification][conventional-breaking]~
[conventional-breaking]: https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-descrip …

chore(concrete_core_wasm): add action to releas concrete-core-wasm

---

concrete-core/src/specification/entities/glwe_ciphertext.rs

chore(core): fix typo in doc

---

concrete-core/Cargo.toml

this is the first step towards having support for Apple Silicon

chore(deps): update concrete-fftw to 0.1.3

---

concrete-core/src/commons/crypto/lwe/seeded_keyswitch.rs

A feature rename was missed for the seeded KSK serialization

chore(core): rename serde feature for seeded KSK

---

concrete-core/src/commons/crypto/ggsw/seeded_levels.rs
concrete-core/src/commons/crypto/ggsw/seeded_standard.rs
concrete-core/src/commons/crypto/secret/glwe.rs

Found during some work on aarch64, algorithms were too complex and causing some issues

refactor(core): refactor some seeded GGSW alogrithms which were too complex

---

concrete-core/src/commons/crypto/secret/glwe.rs

this run : https://github.com/zama-ai/concrete-core/runs/7920921928?check_suite_focus=true#step:7:1154
we use toy example parameters, so lower the error to avoid random tests
failures

chore(core): update some parameters for a flaky test

---

concrete-core/src/commons/crypto/secret/glwe.rs

https://github.com/zama-ai/concrete-core-internal/issues/309

chore(test): fix flaky test with toy parameters

---

concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_bootstrap_key_conversion.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_bootstrap.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
concrete-core/src/backends/cuda/implementation/engines/mod.rs

fix(cuda): add error management for glwe dimension

---

concrete-core-ffi/README.md
concrete-core-wasm/README.md
concrete-core/README.md
concrete-cuda/README.md

https://github.com/zama-ai/products/issues/298
for concrete-core
Links to the user doc are added to the README for Core, FFI and WASM.

chore(core): update user doc links in the readme files

---

concrete-core-ffi/tests/test_lwe_encrypt_mul_cleartext_decrypt.c

chore(test): fix a test that proved to be flaky in the M1 CI

---

.github/workflows/ffi_github_release.yml

chore(ffi): upgrade build machine to a non depecrated macOS for mac

---

concrete-core/src/backends/fftw/private/crypto/ggsw/fourier.rs
concrete-core/src/backends/fftw/private/crypto/wop_pbs/mod.rs
concrete-core/src/backends/fftw/private/crypto/wop_pbs/test.rs
concrete-core/src/commons/math/polynomial/list.rs

closes https://github.com/zama-ai/concrete-core-internal/issues/377
Some vecs cannot be removed currently in the private implementation
Simplified the test part, let me know @Loris-B if everything looks good ?

feat(core): add vertical packing for wop PBS

---

concrete-core-ffi/src/backends/default/engines/entity_deserialization.rs
concrete-core-ffi/src/backends/default/engines/entity_serialization.rs
concrete-core-ffi/tests/test_lwe_bootstrap_key_to_mut_view_conversion.c
concrete-core-ffi/tests/test_lwe_bootstrap_w_bsk_serde.c
concrete-core-ffi/tests/test_lwe_encrypt_keyswitch_w_ksk_serde_decrypt.c

feat(ffi): add LweBootstrapKey64 de/serialization

---

concrete-core-fixture/src/fixture/glwe_to_lwe_secret_key_transformation.rs
concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_1.rs
concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_2.rs
concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_extraction.rs
concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_1.rs
concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_2.rs
concrete-core-fixture/src/fixture/lwe_to_glwe_secret_key_transformation.rs
concrete-core-fixture/src/generation/prototyping/glwe_secret_key.rs
concrete-core-fixture/src/generation/prototyping/lwe_secret_key.rs

chore(fixture): revert change in fixture for LWE/GLWE prototypes transformation

---

concrete-core/src/backends/fftw/implementation/engines/fftw_engine/glwe_ciphertext_conversion.rs
concrete-core/src/backends/fftw/implementation/engines/fftw_engine/glwe_ciphertext_ggsw_ciphertext_discarding_external_product.rs
concrete-core/src/backends/fftw/implementation/engines/fftw_engine/glwe_ciphertext_ggsw_ciphertext_external_product.rs
concrete-core/src/backends/fftw/implementation/engines/fftw_engine/glwe_ciphertexts_ggsw_ciphertext_fusing_cmux.rs
concrete-core/src/backends/fftw/implementation/engines/fftw_engine/lwe_ciphertext_discarding_bootstrap.rs
concrete-core/src/backends/fftw/implementation/engines/fftw_engine/mod.rs

chore(core): factorize FftwError polynomial size check

---

concrete-core/src/backends/fftw/implementation/engines/fftw_engine/lwe_ciphertext_discarding_bit_extraction.rs

https://github.com/zama-ai/concrete-core-internal/issues/407

feat(core): add public API for bit extract over views

---

concrete-core/src/backends/fft/implementation/engines/deserialization.rs
concrete-core/src/backends/fft/implementation/engines/ggsw_ciphertext_conversion.rs
concrete-core/src/backends/fft/implementation/engines/glwe_ciphertext_ggsw_ciphertext_discarding_external_product.rs
concrete-core/src/backends/fft/implementation/engines/glwe_ciphertexts_ggsw_ciphertext_fusing_cmux.rs
concrete-core/src/backends/fft/implementation/engines/lwe_bootstrap_key_conversion.rs
concrete-core/src/backends/fft/implementation/engines/lwe_ciphertext_discarding_bootstrap.rs
concrete-core/src/backends/fft/implementation/engines/serialization.rs

I don't understand why the CI was green but some formatting was wrong and some docstrings should have failed 😕 

chore(core): fix fft backend issues the CI did not pick up

---

concrete-core/src/backends/default/implementation/engines/default_engine/lwe_ciphertext_discarding_public_key_encryption.rs
concrete-core/src/backends/default/implementation/engines/default_engine/lwe_ciphertext_vector_decryption.rs
concrete-core/src/backends/default/implementation/engines/default_engine/lwe_ciphertext_vector_discarding_encryption.rs

fixes doctests that reference deleted concrete-commons crate

fix(core): remove references to deleted concrete-commons crate

---

concrete-core/src/backends/fft/implementation/engines/deserialization.rs
concrete-core/src/backends/fft/implementation/engines/mod.rs
concrete-core/src/backends/fft/implementation/engines/serialization.rs
concrete-core/src/backends/fft/private/crypto/bootstrap.rs
concrete-core/src/backends/fft/private/crypto/ggsw.rs
concrete-core/src/backends/fft/private/crypto/glwe.rs
concrete-core/src/backends/fft/private/math/fft.rs
concrete-core/src/backends/fft/private/math/polynomial.rs
concrete-core/src/backends/fft/private/mod.rs

this pr implements serialization and deserialization for the concrete-fft engine

feat(core): implement serialization for the concrete-fft engine

---

concrete-core/src/commons/crypto/bootstrap/standard/mod.rs
concrete-core/src/commons/crypto/ggsw/standard.rs
concrete-core/src/commons/crypto/gsw/ciphertext.rs
concrete-core/src/commons/crypto/secret/generators/encryption.rs
concrete-core/src/commons/crypto/secret/glwe.rs
concrete-core/src/commons/crypto/secret/lwe.rs
concrete-core/src/commons/math/random/generator.rs
concrete-core/src/commons/math/tensor/tensor.rs

Fixes doc strings + add a test back

fix(core): fix doc strings refering to parallel feature + add back a test

---

concrete-core/src/commons/crypto/secret/glwe.rs

chore(core): fix flaky test for encrypt_glwe_list

---

concrete-csprng/src/seeders/implem/unix.rs

closes https://github.com/zama-ai/concrete-core-internal/issues/415

docs(csprng): add hypotheses of the attack on UnixSeeder

---

Cargo.toml
concrete-core-fixture/src/fixture/lwe_ciphertext_vector_glwe_ciphertext_discarding_private_functional_packing_keyswitch.rs
concrete-tasks/src/test.rs

closes https://github.com/zama-ai/concrete-core-internal/issues/414

feat(core): run tests with debug asserts on

---

concrete-core/src/backends/default/implementation/engines/default_engine/lwe_packing_keyswitch_key_generation.rs

closes https://github.com/zama-ai/concrete-core-internal/issues/256

chore(core): fix packing ksk generation doctests

---

concrete-core/src/backends/default/implementation/engines/default_engine/lwe_ciphertext_discarding_keyswitch.rs

fix(core): fix variance in u64 keyswitch doc test

---

concrete-core/src/commons/crypto/glwe/ciphertext.rs

closes https://github.com/zama-ai/concrete-core-internal/issues/152

chore(core): fix flaky fill_lwe_with_sample_extraction doc test

---

concrete-core-fixture/src/raw/generation.rs
concrete-core/src/backends/default/implementation/engines/activated_generator.rs
concrete-csprng/Cargo.toml
concrete-csprng/src/generators/implem/aarch64/generator.rs
concrete-csprng/src/generators/implem/aarch64/parallel.rs
concrete-csprng/src/main.rs
concrete-csprng/src/seeders/implem/apple_secure_enclave_seeder.rs
concrete-csprng/src/seeders/implem/mod.rs

closees https://github.com/zama-ai/concrete-core-internal/issues/207
- re-use work from this original PR: https://github.com/zama-ai/concrete-core/pull/4
C FFI to follow

feat(csprng): implement AppleSecureEnclaveSeeder

---

concrete-core/Cargo.toml

closes https://github.com/zama-ai/concrete-core-internal/issues/295
FFTW bug report : https://github.com/FFTW/fftw3/issues/294
Credits to @sarah-ek for finding the bug in the first place and the repro code

fix(core): use patched concrete-fftw to avoid fftw generic simd256 bug

---

concrete-core/src/backends/cuda/implementation/engines/cuda_amortized_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_bootstrap_key_conversion.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_bootstrap.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
concrete-core/src/backends/cuda/implementation/engines/mod.rs

fix(cuda): fix checks in Cuda backend

---

.github/workflows/check_commit.yml
.github/workflows/lint.yml

chore(core): only launch lint job on PRs

---

concrete-core/src/backends/fft/implementation/engines/fft_engine/ggsw_ciphertext_conversion.rs
concrete-core/src/backends/fft/implementation/engines/fft_engine/ggsw_ciphertext_discarding_conversion.rs
concrete-core/src/backends/fft/implementation/engines/fft_engine/glwe_ciphertext_ggsw_ciphertext_discarding_external_product.rs
concrete-core/src/backends/fft/implementation/engines/fft_engine/glwe_ciphertexts_ggsw_ciphertext_fusing_cmux.rs
concrete-core/src/backends/fft/implementation/engines/fft_engine/lwe_bootstrap_key_conversion.rs
concrete-core/src/backends/fft/implementation/engines/fft_engine/lwe_ciphertext_discarding_bootstrap.rs
concrete-core/src/backends/fft/implementation/engines/fft_engine/mod.rs
concrete-core/src/backends/fft/implementation/engines/fft_serialization_engine/deserialization.rs
concrete-core/src/backends/fft/implementation/engines/fft_serialization_engine/mod.rs
concrete-core/src/backends/fft/implementation/engines/fft_serialization_engine/serialization.rs
concrete-core/src/backends/fft/implementation/engines/mod.rs

This PR refactors the FFT backend to follow the same structure as the FFTW backend.

chore(core): refactor fft backend

---

concrete-core-fixture/src/fixture/lwe_public_key_generation.rs

fix(core): fix LWE public key generation fixture

---

.github/workflows/aws_tests_gpu.yml
.github/workflows/aws_tests_gpu_slab_beta.yml
ci/slab.toml
concrete-tasks/src/test.rs

A new toolkit has to be used for testing GPU backend. The AMI change reflects this need.

chore(ci): update aws ami used for gpu test suite

---

concrete-core/src/commons/crypto/secret/glwe.rs

chore(core): fix flaky tests

---

concrete-core/src/commons/crypto/secret/lwe.rs

chore(core): fix unused import when __commons_parallel is disabled

---

concrete-cuda/cuda/src/bootstrap_amortized.cuh
concrete-cuda/cuda/src/bootstrap_low_latency.cu
concrete-cuda/cuda/src/bootstrap_low_latency.cuh
concrete-cuda/cuda/src/bootstrap_wop.cuh
concrete-cuda/cuda/src/crypto/bootstrapping_key.cuh
concrete-cuda/cuda/src/crypto/torus.cuh
concrete-cuda/cuda/src/fft/bnsmfft.cuh
concrete-cuda/cuda/src/fft/twiddles.cuh
concrete-cuda/cuda/src/keyswitch.cuh
concrete-cuda/cuda/src/polynomial/functions.cuh
concrete-cuda/cuda/src/polynomial/polynomial.cuh

There were many legacy comments that are not relevant or useful anymore. This PR removes them.

chore(cuda): Remove old comments from concrete-cuda.

---

README.md
concrete-core/Cargo.toml
concrete-cuda/Cargo.toml
concrete-npe/Cargo.toml

chore(core): bump remaining versions

---

concrete-core/benches/bench.rs

adds a benchmark for the fft wop-pbs

feat(core): add woppbs bench

---

concrete-core/src/specification/engines/lwe_ciphertext_vector_discarding_circuit_bootstrap_boolean_vertical_packing.rs

The check on the small_lut_size was too restrictive

feat(core): adjust check in discarding_circuit_bootstrap

---

concrete-core/src/backends/default/implementation/engines/default_serialization_engine/entity_deserialization.rs
concrete-core/src/backends/default/implementation/engines/default_serialization_engine/entity_serialization.rs

PublicKey De/Serialization
cc @leventdem 

feat(core): add LwePublicKey De/Serialization

---

concrete-core/docs/README.md
concrete-core/docs/SUMMARY.md
concrete-core/docs/api_reference/concrete-core-ffi.md
concrete-core/docs/api_reference/concrete-core-wasm.md
concrete-core/docs/backends/activating_backends.md
concrete-core/docs/backends/backend_cuda.md
concrete-core/docs/backends/backend_default.md
concrete-core/docs/backends/backend_fft.md
concrete-core/docs/general_concepts/api_structure.md
concrete-core/docs/general_concepts/memory_management.md
concrete-core/docs/getting_started/quick_start.md
concrete-core/docs/getting_started/supported_data_types.md
concrete-core/docs/getting_started/supported_operations.md
concrete-core/docs/how_to/benchmarking_backends.md
concrete-core/docs/how_to/creating_backends.md
concrete-core/docs/how_to/testing_backends.md

GitBook: [#5] Concrete Core doc edits

docs(core): language edits

---

README.md

chore: update README.md for october release

---

concrete-csprng/Cargo.toml
concrete-csprng/src/main.rs

chore(csprng): fix dry run

---

concrete-core/docs/general_concepts/api_structure.md
concrete-core/docs/general_concepts/memory_management.md
concrete-core/docs/getting_started/quick_start.md
concrete-core/docs/getting_started/supported_data_types.md

docs(core): fix broken links

---

concrete-core/docs/general_concepts/api_structure.md

docs(core): add sentence about vector entities

---

concrete-csprng/Cargo.toml
concrete-csprng/build.rs

fix(csprng): fix build.rs feature checks

---

concrete-core/docs/README.md
concrete-core/docs/SUMMARY.md
concrete-core/docs/backends/backend_cuda.md
concrete-core/docs/backends/backend_default.md
concrete-core/docs/backends/backend_fft.md
concrete-core/docs/general_concepts/api_structure.md
concrete-core/docs/getting_started/quick_start.md
concrete-core/docs/getting_started/supported_data_types.md
concrete-core/docs/getting_started/supported_operations.md

docs(core): update links in user doc to 1.0.1

---

concrete-cuda/cuda/src/bootstrap_amortized.cuh
concrete-cuda/cuda/src/bootstrap_low_latency.cuh
concrete-cuda/cuda/src/polynomial/polynomial.cuh
concrete-cuda/cuda/src/polynomial/polynomial_math.cuh

This PR removes the class PolynomialFourier that wasn't actually used. @bbarbakadze if you think this is not a good idea and this class could be useful let me know :slightly_smiling_face: 

refactor(cuda): remove PolynomialFourier

---

concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_opposite.rs
concrete-core-fixture/src/fixture/mod.rs
concrete-core-test/src/cuda.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_discarding_opposite.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
concrete-core/src/backends/cuda/private/crypto/lwe/list.rs
concrete-core/src/backends/cuda/private/device.rs
concrete-cuda/cuda/include/negation.h
concrete-cuda/cuda/src/CMakeLists.txt
concrete-cuda/cuda/src/negation.cu
concrete-cuda/cuda/src/negation.cuh
concrete-cuda/cuda/src/utils/kernel_dimensions.cuh
concrete-cuda/src/cuda_bind.rs

Implements LWE ciphertext array negation on GPU.

feat(cuda): implement negation of an LWE ciphertext vector

---

concrete-core/src/backends/fft/implementation/engines/fft_engine/ggsw_ciphertext_discarding_conversion.rs
concrete-core/src/backends/fft/private/crypto/ggsw.rs

feat(core): add backward GGSW Fourier conversion to FFT backend

---

concrete-core-bench/Cargo.toml
concrete-core-bench/src/fft.rs
concrete-core-bench/src/main.rs
concrete-core-fixture/Cargo.toml
concrete-core-fixture/src/generation/mod.rs
concrete-core-fixture/src/generation/synthesizing/ggsw_ciphertext.rs
concrete-core-fixture/src/generation/synthesizing/lwe_bootstrap_key.rs
concrete-core-wasm/Cargo.toml
concrete-core/Cargo.toml
concrete-core/src/backends/fft/implementation/engines/fft_parallel_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
concrete-core/src/backends/fft/implementation/engines/fft_parallel_engine/mod.rs
concrete-core/src/backends/fft/implementation/engines/mod.rs
concrete-core/src/commons/crypto/glwe/list.rs
concrete-core/src/commons/crypto/lwe/list.rs

feat(core): add a parallel fft engine to execute PBS in parallel on CPU

---

concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_1.rs
concrete-core-fixture/src/fixture/lwe_ciphertext_discarding_bootstrap_2.rs
concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_1.rs

chore(core): change PBS tests parameters

---

.github/workflows/ffi_github_release.yml
concrete-core-ffi/CMakeLists.txt
concrete-core-ffi/Cargo.toml

chore(ci): enable avx512 builds in the FFI CI

---

concrete-core-test/src/lib.rs

chore(core): restore numbers of samples and repetitions that was accidentally changed

---

concrete-cuda/cuda/src/bootstrap_amortized.cuh
concrete-cuda/cuda/src/bootstrap_low_latency.cuh
concrete-cuda/cuda/src/bootstrap_wop.cuh
concrete-cuda/cuda/src/crypto/torus.cuh
concrete-cuda/cuda/src/polynomial/functions.cuh

chore(cuda): replace casts with cuda intrinsics

---

.github/workflows/aws_tests_gpu_slab_beta.yml
.github/workflows/aws_tests_slab_beta.yml

Adapt workflow to handle new input field.

chore(ci): adapt workflows to v0.10.x of slab ci bot

---

.github/workflows/gpu_benchmark.yml

Set environment variables for CUDA and gcc suite.

chore(ci): set env vars for gpu benchmarks

---

.github/workflows/gpu_benchmark.yml

chore(ci): add build matrix for cuda and gcc versions

---

.github/workflows/gpu_benchmark.yml
ci/benchmark_parser.py
ci/slab.toml

Ci fix AMI and result parsing

---

concrete-cuda/cuda/src/addition.cuh
concrete-cuda/cuda/src/bootstrap_amortized.cuh
concrete-cuda/cuda/src/bootstrap_wop.cuh
concrete-cuda/cuda/src/keyswitch.cuh
concrete-cuda/cuda/src/multiplication.cuh
concrete-cuda/cuda/src/negation.cuh

feat(cuda): Check for errors after each kernel launch.

---

.github/workflows/lint.yml
concrete-core-test/src/cuda.rs

chore(cuda): update ci and reduce samples/repetitions in tests

---

concrete-cuda/cuda/src/bootstrap_amortized.cu
concrete-cuda/cuda/src/bootstrap_low_latency.cu
concrete-cuda/cuda/src/bootstrap_wop.cu
concrete-cuda/cuda/src/negation.cuh

chore(cuda): fix asserts regarding the base log value

---

concrete-core/src/backends/cuda/private/crypto/bootstrap/test.rs
concrete-core/src/backends/cuda/private/device.rs
concrete-core/src/backends/cuda/private/wopbs/mod.rs
concrete-core/src/backends/cuda/private/wopbs/test.rs
concrete-cuda/cuda/include/bootstrap.h
concrete-cuda/cuda/include/keyswitch.h
concrete-cuda/cuda/src/bootstrap_amortized.cu
concrete-cuda/cuda/src/bootstrap_amortized.cuh
concrete-cuda/cuda/src/bootstrap_low_latency.cu
concrete-cuda/cuda/src/bootstrap_low_latency.cuh
concrete-cuda/cuda/src/bootstrap_wop.cu
concrete-cuda/cuda/src/bootstrap_wop.cuh
concrete-cuda/cuda/src/keyswitch.cu
concrete-cuda/cuda/src/keyswitch.cuh
concrete-cuda/cuda/src/negation.cuh
concrete-cuda/src/cuda_bind.rs

feat(cuda): Adds a parameter in the CUDA host functions passing the gpu index that should be used.

---

concrete-core-fixture/src/fixture/lwe_ciphertext_vector_cleartext_vector_discarding_multiplication.rs
concrete-cuda/cuda/src/crypto/bootstrapping_key.cuh
concrete-cuda/cuda/src/fft/bnsmfft.cuh
concrete-cuda/cuda/src/fft/twiddles.cu
concrete-cuda/cuda/src/fft/twiddles.cuh

Fix cuda bootstrap for N = 8192

---

LICENSE
concrete-core-bench/LICENSE
concrete-core-ffi/LICENSE
concrete-core-fixture/LICENSE
concrete-core-representation/LICENSE
concrete-core-test/LICENSE
concrete-core-wasm/LICENSE
concrete-core/LICENSE
concrete-cpu/LICENSE
concrete-csprng/LICENSE
concrete-cuda/LICENSE
concrete-npe/LICENSE

chore(core): update license

---

concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_2.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_amortized_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_bootstrap_key_conversion.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_discarding_bootstrap.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/mod.rs
concrete-core/src/backends/cuda/implementation/engines/mod.rs
concrete-core/src/backends/cuda/private/crypto/bootstrap/test.rs
concrete-core/src/backends/cuda/private/wopbs/test.rs
concrete-cuda/cuda/include/bootstrap.h
concrete-cuda/cuda/src/bootstrap_low_latency.cu
concrete-cuda/cuda/src/bootstrap_low_latency.cuh
concrete-cuda/cuda/src/bootstrap_wop.cu
concrete-cuda/cuda/src/bootstrap_wop.cuh
concrete-cuda/src/cuda_bind.rs

Support N = 4096 and 8192 in the low latency bootstrap

---

concrete-core/src/backends/fft/implementation/engines/fft_engine/lwe_ciphertext_discarding_bootstrap.rs

In the test delta is computed as a scale not as a bit-shift. Previous implementation always encrypt/decrypt '0'

fix(cpu): fix plaintext encoding in pbs_test of fft_backend

---

concrete-core-bench/src/cuda.rs
concrete-core-bench/src/main.rs

fix(cuda): fix cbs+vp benchmark

---

concrete-csprng/src/seeders/implem/unix.rs

chore(doc): fix reference to concrete-core -> concrete-csprng

---

concrete-cuda/cuda/include/boolean_gates.h
concrete-cuda/cuda/src/boolean_gates.cu

https://github.com/zama-ai/concrete-core-internal/issues/506

feat(cuda): add missing boolan gates

---

concrete-core-fixture/src/fixture/lwe_ciphertext_vector_discarding_bootstrap_3.rs
concrete-core-fixture/src/fixture/mod.rs
concrete-core-test/src/cuda.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_amortized_engine/lwe_ciphertext_vector_discarding_bootstrap.rs
concrete-core/src/backends/cuda/implementation/engines/cuda_engine/lwe_bootstrap_key_conversion.rs
concrete-cuda/cuda/src/bootstrap_amortized.cu
concrete-cuda/cuda/src/bootstrap_amortized.cuh
concrete-cuda/cuda/src/bootstrap_low_latency.cuh
concrete-cuda/cuda/src/circuit_bootstrap.cuh
concrete-cuda/cuda/src/crypto/bootstrapping_key.cuh
concrete-cuda/cuda/src/crypto/gadget.cuh
concrete-cuda/cuda/src/polynomial/functions.cuh
concrete-cuda/cuda/src/vertical_packing.cuh

refactor(cuda): Refactor the amortized PBS to support k > 1

---

concrete-core/src/backends/cuda/private/crypto/bootstrap/test.rs
concrete-core/src/backends/cuda/private/crypto/wopbs/test.rs
concrete-core/src/backends/cuda/private/device.rs
concrete-cuda/cuda/include/bootstrap.h
concrete-cuda/cuda/include/circuit_bootstrap.h
concrete-cuda/cuda/src/CMakeLists.txt
concrete-cuda/cuda/src/boolean_gates.cu
concrete-cuda/cuda/src/bootstrap_amortized.cu
concrete-cuda/cuda/src/bootstrap_amortized.cuh
concrete-cuda/cuda/src/circuit_bootstrap.cu
concrete-cuda/cuda/src/circuit_bootstrap.cuh
concrete-cuda/cuda/src/vertical_packing.cuh
concrete-cuda/cuda/src/wop_bootstrap.cuh
concrete-cuda/src/cuda_bind.rs

refactor(cuda): introduce scratch for amortized PBS

---

concrete-cuda/cuda/src/device.cu

fix(cuda): fix multi gpu behavior
